name: 'Build backend images'
description: 'Build API, Scheduler, and Worker images'
inputs:
  dockerhub-username:
    description: 'DockerHub username'
    required: false
  dockerhub-token:
    description: 'DockerHub access token'
    required: false

runs:
  using: "composite"
  steps:
#    - uses: docker/login-action@v2
#      with:
#        username: ${{ inputs.dockerhub-username }}
#        password: ${{ inputs.dockerhub-token }}
    - run: |
        mkdir -p /usr/local/lib/docker/cli-plugins
        curl -SL https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-linux-x86_64 -o /usr/local/lib/docker/cli-plugins/docker-compose
        sudo chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
        docker compose version
      shell: bash
    - run: |
        echo ${{ github.sha }}
        docker compose -f docker-compose.yml build ngrok
      shell: bash
#    - run: |
#        docker push $API_IMAGE
#        docker push $SCHEDULER_IMAGE
#        docker push $WORKER_IMAGE
#      shell: bash
